accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (get_cookie_view, set_cookie_view, set_session_view, get_session_view, MyLogoutView,
                    MyLoginView, AboutMeView, RegisterView, FooBarView, UserListView, UserDetailView,
                    UpdateAvatarView, HelloView)

app_name = "accounts"

urlpatterns = [
    # path("login/",
    #      LoginView.as_view(
    #          template_name="accounts/login.html",
    #          redirect_authenticated_user=True,
    #      ),
    #      name="login"),
    # path("logout/", logout_view, name="logout"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("update_avatar/<int:pk>/", UpdateAvatarView.as_view(), name="update-avatar"),
    path("users/", UserListView.as_view(), name="user-list"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("register/", RegisterView.as_view(), name="register"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

blogapp/urls.py
from django.urls import path
from .views import (ClassBasedView, ArticleDetailView,
                    ArticleListView, LatestArticlesFeed)

app_name = "blogapp"

urlpatterns = [
    path("article_list/", ClassBasedView.as_view(), name="blog"),
    path("articles/", ArticleListView.as_view(), name="articles"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article"),
    path("articles/latest/feed/", LatestArticlesFeed(), name="articles-feed"),
]

module_20/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps


urlpatterns = [

    path("req/", include("requestdataapplication.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("blog/", include("blogapp.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shopapplication.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

accounts/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models


def avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "profiles/profile_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    biography = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

    def __str__(self):
        return self.user.username


class AvatarForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["avatar"]

accounts/views.py
from random import random
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext

from accounts.models import AvatarForm, UserProfile


class HelloView(View):
    welcome_message = _("welcome hello world!")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_string = request.GET.get("items") or 0
        items = int(items_string)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class AboutMeView(TemplateView):
    template_name = "accounts/about-me.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        context["form"] = AvatarForm(instance=profile)
        context["user_profile"] = profile
        return context


class UpdateAvatarView(View):
    def post(self, request, *args, **kwargs):
        profile = get_object_or_404(UserProfile, user=request.user)

        form = AvatarForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Avatar updated successfully!")
            return redirect("accounts:about-me")
        else:
            messages.error(request, "Error updating avatar.")
            return render(request, "accounts/about-me.html", {"form": form})


class UserListView(ListView):
    model = UserProfile
    template_name = "accounts/user_list.html"
    context_object_name = "profiles_list"


class UserDetailView(DetailView):
    model = UserProfile
    template_name = "accounts/user_detail.html"
    context_object_name = "user_profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = AvatarForm(instance=self.object)
        return context


def is_admin_or_owner(user, profile_id):
    return user.is_staff or user.profile.id == profile_id


@method_decorator(user_passes_test(lambda u, pk=None: is_admin_or_owner(u, pk)), name="dispatch")
class UserProfileDetailView(DetailView):
    model = UserProfile
    template_name = "accounts/user_detail.html"
    context_object_name = "profile"

    def post(self, request, *args, **kwargs):
        profile = self.get_object()
        form = AvatarForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:user-detail', pk=profile.id)
        return render(request, self.template_name, {'form': form, 'profile': profile})


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("accounts:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        user_profile, created = UserProfile.objects.get_or_create(user=self.object)

        self.object.user_profile = user_profile
        self.object.save()

        return response


class MyLoginView(LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True


class MyLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        if request.method == "GET":
            return self.get(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    next_page = reverse_lazy("accounts:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(timeout=60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("accounts.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

accounts/templates/accounts/about-me.html
{% extends "accounts/base.html" %}
{% load cache %}

{% block title %}
    About me
{% endblock %}

{% block body %}
        <h1>User info</h1>
    {% cache 100 userinformation user.username %}
        <div>
            Products available: {% now "u" %}
        </div>
        <p>Username: {{ request.user.username }}</p>
        <p>First name: {{ request.user.first_name }}</p>
        <p>Last name: {{ request.user.last_name }}</p>
        <p>Email: {{ request.user.email }}</p>
        <p>Biography: {{ request.user.profile.biography }}</p>
    {% endcache %}

    <form method="post" enctype="multipart/form-data" action="{% url 'accounts:update-avatar' pk=user_profile.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Avatar</button>
    </form>

    {% if user_profile.avatar %}
        <img src="{{ user_profile.avatar.url }}" alt="Avatar">
    {% else %}
        <p>No avatar found for this user.</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "accounts/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

accounts/templates/accounts/update_avatar.html
{% extends "accounts/base.html" %}

{% block title %}
    Update Avatar
{% endblock %}

{% block body %}
    <h1>Update Avatar</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'accounts:update-avatar' pk=user_profile.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends "accounts/base.html" %}

{% block title %}
    User Detail - {{ user_profile.user.username }}
{% endblock %}

{% block body %}
    <h1>User Detail - {{ user_profile.user.username }}</h1>
    <p>First Name: {{ user_profile.user.first_name }}</p>
    <p>Last Name: {{ user_profile.user.last_name }}</p>
    <p>Email: {{ user_profile.user.email }}</p>

    <form method="post" enctype="multipart/form-data" action="{% url 'accounts:update-avatar' pk=user_profile.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Avatar</button>
    </form>

    {% if user_profile.avatar %}
        <img src="{{ user_profile.avatar.url }}" alt="Avatar">
    {% else %}
        <p>No avatar found for this user.</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends "accounts/base.html" %}

{% block title %}
    User List
{% endblock %}

{% block body %}
    <table>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Biography</th>
        </tr>
        {% for profile in profiles_list %}
        <tr>
            <td><a href="{% url 'accounts:user-detail' pk=profile.id %}">{{ profile.user.username }}</a></td>
            <td>{{ profile.user.email }}</td>
            <td>{{ profile.biography }}</td>
        </tr>
        {% endfor %}
    </table>
    <p>Number of users: {{ profiles_list|length }}</p>
{% endblock %}