blogapp/urls.py
from django.urls import path
from .views import (ClassBasedView, ArticleDetailView,
                    ArticleListView, LatestArticlesFeed)

app_name = "blogapp"

urlpatterns = [
    path("article_list/", ClassBasedView.as_view(), name="blog"),
    path("articles/", ArticleListView.as_view(), name="articles"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article"),
    path("articles/latest/feed/", LatestArticlesFeed(), name="articles-feed"),
]

module_20/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps


urlpatterns = [

    path("req/", include("requestdataapplication.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("blog/", include("blogapp.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shopapplication.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

shopapplication/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView, GroupsListView, OrdersListView, OrdersDetailView,
                    OrderCreateView, ProductsDetailsView, ProductsListView, ProductCreateView,
                    ProductUpdateView, ProductDeleteView, OrderUpdateView, OrderDeleteView,
                    ProductsDataExportView, OrdersExportView, ProductViewSet, OrderViewSet,
                    LatestProductsFeed, UserOrdersListView, UserOrdersExportView)

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)
app_name = "shopapplication"


urlpatterns = [
    path("api/", include(routers.urls)),
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductsDetailsView.as_view(), name="product_details"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/export/", ProductsDataExportView.as_view(), name="products_export"),
    path("orders/", OrdersListView.as_view(), name="order_list"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path('orders/export/', OrdersExportView.as_view(), name='orders_export'),
    path("products/latest/feed/", LatestProductsFeed(), name="latest-products-feed"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders_list"),
    path("users/<int:user_id>/orders/export/", UserOrdersExportView.as_view(), name="user_orders_export"),
]

shopapplication/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар, который
    можно продавать в интернет-магазине.

    Заказы тут: :model:'shopapplication.Order'
    """
    class Meta:
        ordering = ["name", "price"]
        # db_table = "shopapplication_product"
        verbose_name_plural = _("Products")
        verbose_name = _("Product")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=True, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=True)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def get_absolute_url(self):
        return reverse("shopapplication:product_details", kwargs={"pk": self.pk})

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) <= 20:
    #         return self.description
    #     return self.description[:15] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=100, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name_plural = _("Orders")
        verbose_name = _("Order")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    archived = models.BooleanField(default=True)
    receipt = models.FileField(null=True, upload_to="orders/receipts/")
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

shopapplication/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view для интернет-магазина: по товарам, заказам и т.д.
"""
import logging
from timeit import default_timer
from csv import DictWriter

from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from django.db.models import Sum, F, ExpressionWrapper, DecimalField
from django.db.models.functions import Coalesce
from django.http import (HttpResponse, HttpRequest,
                         HttpResponseRedirect, JsonResponse)
from django.shortcuts import (render, redirect, reverse, get_object_or_404)
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import (ListView, DetailView, DeleteView,
                                  CreateView, UpdateView)
from rest_framework.parsers import MultiPartParser
from rest_framework.viewsets import ModelViewSet
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.decorators import action
from django_filters.rest_framework import DjangoFilterBackend

from accounts.models import UserProfile
from .common import save_csv_products
from .models import Product, Order, ProductImage
from .forms import ProductForm, GroupForm
from .serializers import ProductSerializer, OrderSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse

logger = logging.getLogger(__name__)


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностей товара.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    search_fields = [
        "name",
        "description"
    ]

    filterset_fields = [
        "id",
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "id",
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrives **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response. Product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super.retrieve(*args, **kwargs)

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        print("Hello products list")
        return super().list(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content_Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "id",
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(methods=["post"], detail=False, parser_classes=[MultiPartParser], )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    """
    Набор представлений для действий над Order.

    Полный CRUD для сущностей заказа.
    """

    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    search_fields = [
        "delivery_address",
        "user",
    ]

    filterset_fields = [
        "id",
        "delivery_address",
        "promocode",
        "created_at",
        "user",
        "products",
        "archived",
    ]
    ordering_fields = [
        "id",
        "delivery_address",
        "created_at",
        "user",
        "products",
    ]


class ShopIndexView(View):
    """Представление для главной страницы магазина."""

    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Обработчик GET запроса для отображения главной страницы магазина.

        :param request: HttpRequest объект запроса.
        :type request: HttpRequest
        :return: HttpResponse объект с отображением главной страницы магазина.
        :rtype: HttpResponse
        """
        products = [
            ("Laptop", 1299),
            ("Desktop", 1420),
            ("Smartphone", 399),
            ("Mouse", 15),
            ("Camera 'Tapo C310'", 12),
            ("USB Cable", 2.99),
        ]

        vacuum_cleaners = [
            ("Samsung", 356),
            ("Bosch", 412),
            ("Zelmer", 398),
            ("Philips", 356),
            ("Sony", 411),
            ("DeWalt", 465),
        ]
        context = {
            "time_running": round(default_timer(), 2),
            "products": products,
            "vacuumcleaners": vacuum_cleaners,
            "items": 5,
        }
        logger.debug("Products for shop index: %s", products, vacuum_cleaners)
        logger.info("Rendering shop index")
        print("shop index context", context)
        return render(request,
                      "shopapplication/shop-index.html", context=context)


class GroupsListView(View):
    """Представление для отображения списка групп пользователей."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Обработчик GET запроса для отображения списка групп пользователей.

        :param request: HttpRequest объект запроса.
        :type request: HttpRequest
        :return: HttpResponse объект ответа с отображением списка групп.
        :rtype: HttpResponse
        """
        groups = Group.objects.prefetch_related("permissions").all()
        context = {
            "form": GroupForm,
            "groups": groups,
        }
        return render(request,
                      "shopapplication/groups-list.html", context=context)

    def post(self, request: HttpRequest):
        """
        Обработчик POST запроса для создания новой группы пользователей.

        :param request: HttpRequest объект запроса.
        :type request: HttpRequest
        :return: HttpResponseRedirect объект перенаправления на
         текущую страницу после создания группы.
        :rtype: HttpResponseRedirect
        """
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductsDetailsView(DetailView):
    """Представление для отображения деталей продукта."""

    template_name = "shopapplication/product-details.html"
    # model = Product
    context_object_name = "product"
    queryset = Product.objects.all()


class ProductsListView(ListView):
    """Представление для отображения списка продуктов."""

    template_name = "shopapplication/products-list.html"
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class OrdersListView(LoginRequiredMixin, ListView):
    """Представление для отображения списка заказов."""

    queryset = (Order.objects
                .select_related("user")
                .prefetch_related("products")
                )


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    """Представление для отображения деталей заказа."""

    permission_required = ["shopapplication.view_order",
                           "shopapplication.view_user", ]
    queryset = (Order.objects
                .select_related("user")
                .prefetch_related("products")
                )


class ProductCreateView(CreateView):
    """Представление для создания нового продукта."""

    model = Product
    fields = ["name", "price", "discount",
              "description", "created_by", "preview"]
    success_url = reverse_lazy("shopapplication:products_list")


class OrderCreateView(PermissionRequiredMixin, CreateView):
    """Представление для создания нового заказа."""

    permission_required = "shopapplication.view_order"
    model = Order
    fields = "products", "delivery_address", "promocode", "user"
    success_url = reverse_lazy("shopapplication:order_list")


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    """Представление для обновления информации о продукте."""

    model = Product
    # fields = ["name", "price", "discount", "description",
    # "created_by", "preview"]
    success_url = reverse_lazy("shopapplication:products_list")
    template_name = "shopapplication/product_update_form.html"
    form_class = ProductForm

    def test_func(self):
        """
        Проверяет, имеет ли текущий пользователь право редактировать.

        Данный продукт.

        :return: True, если пользователь является суперпользователем
        или имеет право изменять продукт и является создателем продукта;
        в противном случае - False.
        :rtype: bool
        """
        user = self.request.user
        product = self.get_object()

shopapplication/templates/shopapplication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Shop application
        {% endblock %}
    </title>
</head>
<body>
{% load i18n %}

{% block body %}
    <h2> Welcome to our application! </h2>
{% endblock %}

<div>
    {% now "H:i" %}
</div>
<div>
    {% now "l" as current_weekday %}
    <h3> {% translate "Today is" %}: {{ current_weekday }} </h3>
</div>
</body>
</html>

shopapplication/templates/shopapplication/create-order.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
               Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_list' %}">
            <h2>
                Back to orders list
            </h2>

        </a>
    </div>
{% endblock %}

shopapplication/templates/shopapplication/groups-list.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
        <h3>No groups yet</h3>
        {% else %}
            <ul>
                {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                            </li>
                        {% endfor %}

                    </ul>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

shopapplication/templates/shopapplication/order_confirm_delete.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Confirm delete {{ object.delivery_address }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete № {{ object.pk }} order?</h1>
    <br>
     <div>
        <a href="{% url 'shopapplication:order_details' pk=object.pk %}">
            <h2>
                Back to order
            </h2>

        </a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete order</button>
        </form>
    </div>

{% endblock %}

shopapplication/templates/shopapplication/order_detail.html
{% extends "shopapplication/base.html" %}

{% load i18n %}

{% block title %}
    {% translate "Order" %} № {{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>{% translate "Order" %} № {{ object.pk }}</h1>
    <div>
        <p>{% translate "Delivery address" %}: {{object.delivery_address}}</p>
        <p>{% translate "Promocode" %}: <code>{{ object.promocode }}</code></p>
        <p>{% translate "Order by" %}: {%firstof object.user%}</p>
        <div>
            {% translate "Products in order" %}:
            <ul>
                {% for product in object.products.all %}
                <li>
                    {{ product.name }} for ${{ product.price }}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_update' pk=object.pk %}">{% translate "Update order" %}</a>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_delete' pk=object.pk %}">{% translate "Delete order" %}</a>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_list' %}">
            <h2>{% translate "Back to order list" %}</h2></a>
    </div>
{% endblock %}

shopapplication/templates/shopapplication/order_form.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Create Order
{% endblock %}

{% block body %}
    <h1>Create a New Order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_list' %}">Back to Orders List</a>
    </div>
{% endblock %}

shopapplication/templates/shopapplication/order_update_form.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update order № {{ object.pk }}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
               Update
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapplication:order_details' object.pk %}">
            <h2>
                Back to order № {{ object.pk }}
            </h2>
        </a>
    </div>
{% endblock %}

shopapplication/templates/shopapplication/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

shopapplication/templates/shopapplication/product_confirm_delete.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
     <div>
        <a href="{% url 'shopapplication:product_details' pk=object.pk %}">
            <h2>
                Back to product
            </h2>

        </a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive product</button>
        </form>
    </div>

{% endblock %}

shopapplication/templates/shopapplication/product_update_form.html
{% extends "shopapplication/base.html" %}

{% block title %}
    Update Product: {{ product.name }}
{% endblock %}

{% block body %}
    <h1>Update Product: <strong>{{ product.name }}</strong></h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        {% if perms.shopapplication.change_product and user == product.created_by %}
            <a href="{% url 'shopapplication:product_delete' pk=product.pk %}">Delete Product</a>
        {% endif %}
    </div>
    <div>
            <a href="{% url 'shopapplication:products_list' %}">Back to Product List</a>
    </div>
{% endblock %}

shopapplication/templates/shopapplication/products-list.html
{% extends "shopapplication/base.html" %}

{% load i18n %}

{% block title %}
    {% translate "Products list" %}
{% endblock %}


{% block body %}
    <h1>{% translate "Products" %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count product_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ product_count }} products.
            {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
            <div>
                <p><a href="{% url 'shopapplication:product_details' pk=product.pk%}">
                    {% translate "Name" context "product name" %}: {{product.name}}</a></p>
                <p>{% translate "Description" %}: {{product.description}}</p>
                <p>{% translate "Price" %}: {{product.price}}</p>
                {% translate "no discount" as no_discount %}
                <p>{% translate "Discount" %}: {% firstof product.discount no_discount %}</p>
                <p>{% translate "Created by" %}: {{ product.created_by.username }}</p>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
            {% endfor %}
        </div>


        {% else %}
            {% url 'shopapplication:product_create' as create_product_url %}
            {% blocktranslate %}
        <h3>No products yet</h3>
            <a href="{{ create_product_url }}"
                >Create a new one</a>
            {% endblocktranslate %}
        {% endif %}

        {% if perms.shopapplication.add_product %}
            <div>
                <a href="{% url 'shopapplication:product_create' %}"
                >{% translate "Create a new product" %}</a>
            </div>
        {% else%}
            <p>{% translate "You don't have permission to create products." %}</p>
        {% endif %}
{% endblock %}

shopapplication/templates/shopapplication/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

shopapplication/templates/shopapplication/shop-index.html
{% extends "shopapplication/base.html" %}
{% load cache %}

{% block title %}
    Shop index
{% endblock %}


{% block body %}
    <h1>Welcome to our Shop application!</h1>
    <h2>Today we can offer for you:</h2>
    <h3>Computer Technology Department</h3>

    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} for $ {{ price }}</li>
                {% if name|length_is:"6" %}
                    <span>Congratulations! This product today is lucky, you can receive a discount of 19.99%.</span>
                {% elif name|length_is:"10" %}
                    <span>Congratulations! This product today is lucky, you can receive a discount of 9.99%.</span>
                {% else %}
                    <span>Please ask the seller about the discount.</span>
                {% endif %}
            {% empty %}
                We have no products today!
            {% endfor %}
        </ul>
    </div>

    <h3>Vacuum Cleaners Department</h3>

    <div>
        <ul>
            {% for name, price in vacuumcleaners %}
                <li>{{ name }} for $ {{ price }}</li>
                {% if price == 465 %}
                    <span>Congratulations! This product is lucky today, you can receive a discount of 11.11%.</span>
                {% elif name|length_is:"4" %}
                    <span>Congratulations! This product is lucky today, you can receive a discount of 9.99%.</span>
                {% elif "W" and "h" in name|title %}
                    <span>Congratulations! This product is lucky today, you can receive a discount of 15.99%.</span>
                {% else %}
                    <span>Please ask the seller about the discount.</span>
                {% endif %}
            {% empty %}
                We have no products today!
            {% endfor %}
        </ul>
    </div>

    <h3>Available pages:</h3>
    <ul>
        <li><a href="{% url 'shopapplication:index' %}">Start page</a></li>
        <li><a href="{% url 'shopapplication:groups_list' %}">Groups</a></li>
        <li><a href="{% url 'shopapplication:products_list' %}">Products</a></li>
        <li><a href="{% url 'shopapplication:order_list' %}">Orders</a></li>
        <li><a href="http://127.0.0.1:8000/en/shop/api/products/">API Products</a></li>
        <li><a href="http://127.0.0.1:8000/en/shop/api/orders/">API Orders</a></li>
    </ul>

    {% if not products and not vacuumcleaners %}
        <p>No available links.</p>
    {% endif %}
    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>

    {% cache 60 time %}
    <div>
        Time running: {{ time_running }}
    </div>
    {% endcache %}

{% endblock %}

shopapplication/templates/shopapplication/user_orders_list.html
{% extends "shopapplication/base.html" %}
{% load cache %}

{% block body %}
  <h1>User {{ user.username }} has completed the following order(s):</h1>
  {% cache 120 user_orders user.id %}
    {% if orders %}
      <ul>
        {% for order in orders %}
          <li>Order № {{ order.id }} at {{ order.created_at }}</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>User {{ user.username }} has no orders yet.</p>
    {% endif %}
  {% endcache %}
{% endblock %}